HOST: str = "127.0.0.1"
PORT: int = 8001
RELOAD: bool = False
WORKERS: int = 4


ALLOWED_ORIGINS: list = [
    "http://127.0.0.1",
    "http://127.0.0.1:8080",
]
ALLOW_CREDENTIALS: bool = True
ALLOWED_METHODS: list = [
    "GET",
    "POST",
    "PUT",
    "DELETE",
]
ALLOWED_HEADERS: list = [
    "Authorization",
]


# A new SECRET_KEY can be generated by `openssl rand -hex 32`
SECRET_KEY = "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30
